version: "2"

plugins:
  nodesecurity:
    enabled: true

  editorconfig:
    enabled: true

  markdownlint:
    enabled: true

  duplication:
    enabled: true
    config:
      languages:
      - javascript

  eslint:
    enabled: true
    channel: eslint-5

  fixme:
    enabled: true

exclude_patterns:
  - "LICENSE"
  - ".*"
  - "**/*.*"
  - "!**/*.js"
  - "!**/*.md"
