language: node_js

node_js:
  - '12'

cache:
  yarn: true
  directories:
    - node_modules

install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./codeclimate
  - chmod +x ./codeclimate
  - yarn install --silent

script:
  - ./codeclimate before-build

  - commitlint-travis
  - yarn lint
  - yarn test

  - NODE_ENV=production yarn build --bail

  - ./codeclimate format-coverage ./coverage/lcov.info --input-type lcov
  - ./codeclimate after-build --exit-code $TRAVIS_TEST_RESULT
