name: Build

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/build.yml'
      - 'package.json'
      - 'yarn.lock'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['14']
    name: Node ${{ matrix.node }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: yarn install --silent --frozen-lockfile --prefer-offline

      - name: Eslint
        run: yarn eslint . --max-warnings 0

      - name: Prettier
        run: yarn prettier . --check

      - name: Publish Testing Reports
        uses: paambaati/codeclimate-action@v2.7.4
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_TOKEN }}
        with:
          coverageCommand: yarn test
          coverageLocations: |
            ${{github.workspace}}/coverage/*.lcov:lcov

      - name: Build
        run: NODE_ENV=production yarn build --bail
